baseURL = "https://tsingson.github.io"
relativeurls = false
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "三明智"                    # site title  # 网站标题
theme = "zozo"
hasCJKLanguage = true                # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
summaryLength = 100
paginate = 4                         # shows the number of articles  # 首页显示文章数量
enableEmoji = true
googleAnalytics = ""                 # your google analytics id
disqusShortname = ""                 # your discuss shortname
publishDir =                "../tsingson.github.io"
preserveTaxonomyNames = false
[author]                             # essential                     # 必需
  name = "tsingson"

[blackfriday]
  angledQuotes = true
#  extensions = ["hardLineBreak"]
  fractions = false
  plainIDAnchors = true
  smartypants = false

[[menu.main]]                        # config your menu  # 配置菜单
  name = "首页"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "技术"
  weight = 20
  identifier = "tech"
  url = "/tech/"
[[menu.main]]
  name = "设计"
  weight = 30
  identifier = "design"
  url = "/design/"
[[menu.main]]
  name = "摄影"
  weight = 30
  identifier = "photography"
  url = "/photography/"
[[menu.main]]
  name = "音乐"
  weight = 40
  identifier = "music"
  url = "/music/"
[[menu.main]]
  name = "Tags"
  weight = 50
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "关于"
  weight = 60
  identifier = "about"
  url = "/about/about-me/"

[params]
  subTitle = "programming.design.music"                                       # site's subTitle  # 网站二级标题
  footerSlogan = "技术.设计.音乐"                                          # site's footer slogan  # 网站页脚标语
  keywords = ["Hugo", "theme","zozo"]                                  # site's keywords  # 网站关键字
  description = "三明智 tsingson 的技术.设计.音乐札记"                        # site's description  # 网站描述

# mathjax
  enableMathJax = true                                                 # enable mathjax  # 是否使用mathjax（数学公式）
  enableSummary = true                                                 # display the article summary  # 是否显示文章摘要

 [permalinks]
#   post = "/:year/:month/:title/"
  posts = "/:slug"
[taxonomies]
    category = "categories"
    series = "series"
   tags = "tags"

[params.valine]
  enable = false
  appId = ""
  appKey = ""
  placeholder = " "
  visitor = true

[social]
  github = "https://github.com/tsingson"
  twitter = "https://twitter.com/tsingson"
  # facebook = " "
  # weibo = ""
  # instagram = ""
